### PR TITLE
fix: Blank page on settings while loading

### LINKED ISSUE #1171: When entering settings page, everything is black for a while until it loads
Consider fixing it by showing the loader as originally with the full page layout

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #1171

### CODE REVIEW

File: webapp/src/modules/contract/selectors.ts [hunk 1]
```diff
@@ -15,16 +12,12 @@ export const getContract = createSelectorCreator(defaultMemoize, isEqual)<
...
   Partial<Contract>,
-  ReturnType<typeof getLoading>,
   ReturnType<typeof getContracts>,
   Contract | null
 >(
   (_state: RootState, query: Partial<Contract>) => query,
-  getLoading,
   getContracts,
-  (query: Partial<Contract>, loading: LoadingState, contracts: Contract[]) => {
-    if (isLoadingType(loading, FETCH_CONTRACTS_REQUEST)) return null
```
Comment (fzavalia) [inline webapp/src/modules/contract/selectors.ts:26]: This was unnecessary and bringing problems

**Review by LautaroPetaccio — APPROVED** [review]

**Review by LautaroPetaccio — APPROVED** [review]
