### PR TITLE
fix: user stores responsiveness + transation history

### LINKED ISSUE #504: Make tables in store pages responsive
Make tables in store pages responsive

Make sidebar in mystore accessible (currently it disappears and there's no way to navigate)

### PR DESCRIPTION
**Pull request by cazala**
Closes #504

This PR:

- Fixes the responsiveness of the `Sales` and `On Sale` sections of `My Store`. 
- Since the `CurrentAccountSidebar` was completely removed on mobile, it was not possible to navigate the `My Store` page, so I added some `Tabs` to allow navigation on this view on mobile.
- Added the sale `type` to the sales information in `Sales`, `On Sale`, and `TransactionHistory`.
- I also took the chance to get rid of the deprecated `Responsive` component and replace it with `Mobile` and `NotMobile`. 
- Finally, I modified the `TransactionHistory` component to use the new `/sales` API, added pagination to it, and made it so it support both `NFT` and `Item`, so I added it to the `ItemDetail` as well:

My Store responsive tables:
Screen Shot 2021-12-30 at 12 31 43

ItemDetail with latest sales:
Screen Shot 2021-12-30 at 18 39 20

### CODE REVIEW

**Comment by fzavalia** [comment]
image

When viewAsGuest is present you should not show the tabs for the current user. It should just show things as if it were a different user than the one connected.

**Comment by fzavalia** [comment]
Seems to be also appearing when not in the my store page. For example, I'm in collectibles and can still see bids, settings and collections which should only be available in my store

image

**Comment by cazala** [comment]
fixed @fzavalia 👍

File: webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx [hunk 1]
```diff
@@ -28,56 +37,49 @@ const formatDateTitle = (updatedAt: number) => {
...
+      if ('tokenId' in asset) {
+        params.tokenId = asset.tokenId
+      } else {
+        params.itemId = asset.itemId
+      }
+      saleAPI
+        .fetch(params)
+        .then(response => {
+          setSales(response.data)
+          setTotalPages((response.total / ROWS_PER_PAGE) | 0)
```
Comment (fzavalia) [inline webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx:66]: Why the `| 0`?

**Review by fzavalia — APPROVED** [review]
LGTM!

File: webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx (hunk 1 above)
Comment (cazala) [reply webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx:66]: it’s like Math.floor(), converts float to int (which removes the decimal part).

`2.5 | 0 // —> 2`

Comment (fzavalia) [reply webapp/src/components/AssetPage/TransactionHistory/TransactionHistory.tsx:66]: cool
