### PR TITLE
fix: Wait until finish loading to render assets

### LINKED ISSUE #1592: When switching from My Assets to My List the items can display the on sell icon
## 🎉 Description

When switching a bit fast from My Assets to My List, the view gets stuck at the one that is used in My Assets. This might be due to a race condition on the `setView` action that ends up overwriting the views when switching between one another.

Steps to reproduce:
1. Have several items favorited and some owned ones in the wallet.
2. Go to My Assets and kind of fast, click on the My List tab
3. The items in My List tab will appear with the on sale icon.

### PR DESCRIPTION
**Pull request by kevinszuchet**
Closes #1592

### CODE REVIEW

**Review by meelrossi — APPROVED** [review]

File: webapp/src/components/AssetList/AssetList.tsx [hunk 1]
```diff
@@ -91,7 +91,7 @@ const AssetList = (props: Props) => {
         </>
       ) : null}
       <Card.Group>
-        {assets.length > 0
+        {assets.length > 0 && (!isLoading || (isLoading && isLoadingMore))
```
Comment (kevinszuchet) [inline webapp/src/components/AssetList/AssetList.tsx:94]: I think in the second statement: `isLoading && isLoadingMore` the `isLoading` is redundant.

`(!isLoading && isLoading) || (!isLoading && isLoadingMore)` could be written as: `!isLoading || isLoadingMore`

**Review by kevinszuchet — COMMENTED** [review]
Nice approach!

I left a minor comment to refactor a comparison statement.

File: webapp/src/components/AssetList/AssetList.tsx (hunk 1 above)
Comment (LautaroPetaccio) [reply webapp/src/components/AssetList/AssetList.tsx]: You're completely right! Removed it!

**Review by meelrossi — APPROVED** [review]

**Review by meelrossi — APPROVED** [review]
