### PR TITLE
fix: Redirect to list after creating one

### LINKED ISSUE #1862: Create a new list from the lists page doesn't redirect to the newly created list
## 🎉 Description

When creating a new list, the user is not redirected to the created list. Fix this by making the creation of lists redirect the user to the page of the created list.

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
Closes #1862

### CODE REVIEW

**Review by kevinszuchet — APPROVED** [review]
Touche 🖨️

File: webapp/src/modules/favorites/sagas.ts [hunk 1]
```diff
@@ -414,6 +415,9 @@ export function* favoritesSaga(getIdentity: () => AuthIdentity | undefined) {
         description
       })
       yield put(createListSuccess(list))
+      if (pathname === locations.lists()) {
+        yield put(push(locations.list(list.id)))
+      }
```
Comment (kevinszuchet) [inline webapp/src/modules/favorites/sagas.ts:420]: With this, we are losing the toast that appeared after creating a new list. How could we keep both mechanisms?

Comment (kevinszuchet) [reply webapp/src/modules/favorites/sagas.ts:420]: My bad, the toast never appeared before
