### PR TITLE
feat: use and show gas limit correctly. Fix tx

### LINKED ISSUE #674: Use gas price on transaction
Use gasPriceLimit to send the bid transaction

### PR DESCRIPTION
**Pull request by NicoSantangelo**
Closes #674

### CODE REVIEW

File: webapp/src/modules/auction/sagas.js [hunk 1]
```diff
@@ -9,8 +10,12 @@ import {
   bidOnParcelsSuccess,
   bidOnParcelsFailure
 } from './actions'
+import { getParams } from './selectors'
+import { locations } from 'locations'
 import { splitCoodinatePairs } from 'shared/coordinates'
 
+const ONE_BILLION = 1000000000 // 1.000.000.000
```
Comment (cazala) [inline webapp/src/modules/auction/sagas.js]: 💰
