### PR TITLE
fix: show adjacent estates separated

### LINKED ISSUE #388: Adjacent Estates from different owners are rendered as one
Adjacent Estates from different owners are rendered as one

different-estates

### PR DESCRIPTION
**Pull request by cazala**
Closes #388

Adjacent estates from different owners were shown as one single estate:

different-estates

This PR fixes that:

screen shot 2018-08-28 at 4 57 57 pm

### CODE REVIEW

File: shared/parcel.js [hunk 1]
```diff
@@ -84,8 +84,11 @@ export function areConnected(parcels, parcelId, sideId) {
   if (parcel.district_id && sameDistrict) {
     return true
   }
-  const sameOwner = parcel.owner === sideParcel.owner
-  return parcel.estate_id && parcel.owner && sameOwner
+  const sameEstate = parcel.estate_id === sideParcel.estate_id
+  if (parcel.estate_id && sameEstate) {
```
Comment (NicoSantangelo) [inline shared/parcel.js]: why not `return parcel.estate_id && parcel.estate_id === sideParcel.estate_id` or
```
const isSameEstate = parcel.estate_id === sideParcel.estate_id
return parcel.estate_id && isSameEstate
```

Comment (cazala) [reply shared/parcel.js]: I just copied the style of the lines above: 

```js
const sameDistrict = parcel.district_id === sideParcel.district_id
  if (parcel.district_id && sameDistrict) {
    return true
  }
```

but I can change it
