### PR TITLE
fix: period dropdown placeholder

### LINKED ISSUE #1148: Add placeholder for the rental period dropdown instead of having a default value
The current implementation always shows a default value for the periods dropdown:

But it should show only a placeholder with the "Select period" text.

### PR DESCRIPTION
**Pull request by flobarreto**
closes #1148

### CODE REVIEW

File: webapp/src/components/AssetPage/SaleRentActionBox/PeriodsDropdown/PeriodsDropdown.tsx [hunk 1]
```diff
@@ -29,6 +39,8 @@ const Trigger = ({ period }: { period: RentalListingPeriod }) => {
 }
 
 const PeriodsDropdown = ({ value, periods, className, onChange }: Props) => {
+  const [isOpenDropdown, setIsOpenDropdwon] = useState(false);
```
Comment (juanmahidalgo) [inline webapp/src/components/AssetPage/SaleRentActionBox/PeriodsDropdown/PeriodsDropdown.tsx:42]:
```suggestion
  const [isOpenDropdown, setIsOpenDropdown] = useState(false);
```
small typo here

File: webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx [hunk 2]
```diff
@@ -104,7 +104,7 @@ const SaleRentActionBox = ({
   const handleOnRent = useCallback(() => {
     if (!!authorization && hasAuthorization(authorizations, authorization)) {
```
Comment (juanmahidalgo) [inline webapp/src/components/AssetPage/SaleRentActionBox/SaleRentActionBox.tsx:105]:
```suggestion
    if (!!authorization && hasAuthorization(authorizations, authorization) && selectedRentalPeriodIndex !== undefined) {
```
what if we add this check here so we avoid the ternaries from below? 
like: `onRent(selectedRentalPeriodIndex ? selectedRentalPeriodIndex : 0)`, it would turn back to `onRent(selectedRentalPeriodIndex)`
