### PR TITLE
fix: Don't make get contracts request on startup

### LINKED ISSUE #1136: Evaluate how getContracts can be optimized so it is not called immediately when entering the app
Currently, when entering the app, a request to fetch contracts us being made to the nft-server. 
This request will fetch the subgraphs for absolutely all collections, including the thousands upon thousands of collections. 
This does not only cause lots of queries to the subgraph, but consumes a lot of cpu.
This has to be optimized in some way.

Ideas: 
- The request done in the marketplace is always the same, we can cache the contracts in memory and just fetch for newer contracts on each request.
- Don't fetch all contracts on start, just fetch all on the Settings page were authorizations are required. Ad hoc call for contracts that are required at the moment.

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #1136 

On startup the application was sending a request to the nft server to fetch absolutely all decentraland contracts including collections available.

This was unnecessary and caused loading issues both on the frontend and the backend.

Fetching the contracts also triggered the fetch of all authorizations for the connected user. Why would the user need all authorizations on startup?

The problem of having all contracts and authorizations at startup is that the whole application was coded with always having all contracts and authorizations available making any change difficult to make.

There are 2 kind of decentraland contracts. The static ones such as the ones we know exist like LAND, Estates, Names, etc. On the other hand we have the dynamic ones that are Wearables and Emotes, created by dozens everyday.

At startup we can have all static contracts defined already on the redux store. All dynamic ones will be added to the store as the nfts are fetched from the backed. 

But what happens with authorizations? 

The only page that requires all authorizations is the settings page. The request is done only on this page. Just by moving the request here, the load is diminished by a high magnitude. On the settings page, all contracts and all authorizations are fetched as in this page the user can enable or disable approvals.

On the rest of the application, there is no need to have all authorizations at hand all the time. So they can be requested individually for the required NFT.

### CODE REVIEW

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx [hunk 1]
```diff
@@ -23,18 +28,64 @@ const AuthorizationModal = (props: Props) => {
...
+    if (
+      !isAuthorized(authorization, authorizations) &&
+      !hasFetchedAuthorizations.current
+    ) {
+      hasFetchedAuthorizations.current = true
+      onFetchAuthorizations([authorization])
+    }
+  }, [authorization, authorizations, onFetchAuthorizations])
+
+  useEffect(() => {
```
Comment (fzavalia) [inline webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:59]: Fetches the name of the contract to replace the stub matic collection name if that is the case

File: webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.tsx [hunk 2]
```diff
@@ -74,95 +76,109 @@ const AuthorizationStep = (props: Props) => {
...
-      <Modal.Actions className={styles.actions}>
-        {isConfirmingAuthorization ? (
-          <div className={styles.confirmTransaction}>
-            <Loader
-              active
-              size="small"
-              className={styles.confirmTransactionLoader}
-            />
-            <p>{t('rental_modal.authorization_step.confirm')}</p>
+      {isFetchingAuthorizations ? (
```
Comment (fzavalia) [inline webapp/src/components/Modals/RentalListingModal/AuthorizationStep/AuthorizationStep.tsx:90]: Added a little spinner to the rentals modal for when authorizations are being fetched.

File: webapp/src/components/SettingsPage/SettingsPage.tsx [hunk 3]
```diff
@@ -38,8 +38,17 @@ const SettingsPage = (props: Props) => {
     }
   }, [isConnecting, wallet, onNavigate])
 
+  useEffect(() => {
```
Comment (fzavalia) [inline webapp/src/components/SettingsPage/SettingsPage.tsx:41]: Will fetch contracts when entering the page and when the address changes. 
It is possible to store if they were already fetched for the user once so thay are not fetched everytime the user enters the page in the same session.

File: webapp/src/components/SettingsPage/SettingsPage.tsx [hunk 4]
```diff
@@ -203,13 +227,66 @@ const SettingsPage = (props: Props) => {
...
+                              authorizedAddress: collectionStore.address,
+                              contractAddress: manaMatic.address,
+                              contractName: ContractName.MANAToken,
+                              chainId: manaMatic.chainId,
+                              type: AuthorizationType.ALLOWANCE
+                            }}
+                          />
+                        </div>
+
+                        <div className="authorization-checks">
```
Comment (fzavalia) [inline webapp/src/components/SettingsPage/SettingsPage.tsx:265]: Added the mana atuhorization for rentals that was missing

File: webapp/src/components/SettingsPage/SettingsPage.tsx [hunk 5]
```diff
@@ -203,13 +227,66 @@ const SettingsPage = (props: Props) => {
...
                               address: wallet.address,
-                              authorizedAddress: bids.address,
+                              authorizedAddress: bidsEthereum.address,
                               contractAddress: manaEthereum.address,
                               contractName: ContractName.MANAToken,
                               chainId: manaEthereum.chainId,
                               type: AuthorizationType.ALLOWANCE
                             }}
                           />
+                          <Authorization
```
Comment (fzavalia) [inline webapp/src/components/SettingsPage/SettingsPage.tsx:237]: Added the bids authorization for matic that was missing

File: webapp/src/modules/contract/sagas.spec.ts [hunk 6]
```diff
@@ -8,15 +8,16 @@ import {
...
+describe('when handling the fetch contracts request', () => {
   let mockGetContracts: jest.SpyInstance<Promise<Contract[]>>
 
   afterEach(() => {
     mockGetContracts.mockClear()
   })
 
   describe('when the api call is successful', () => {
-    it('should put a success action with contracts', () => {
+    // TODO: handleFetchContractsSuccess is breaking the test, fix it.
```
Comment (fzavalia) [inline webapp/src/modules/contract/sagas.spec.ts:19]: I skipped the tests that were broken with this changes in order to be able to progress. Will fix and add more tests next

File: webapp/src/modules/contract/sagas.ts [hunk 7]
```diff
@@ -35,3 +47,206 @@ export function* handleFetchContractsRequest() {
     )
   }
 }
+
+export function* handleFetchContractsSuccess() {
```
Comment (fzavalia) [inline webapp/src/modules/contract/sagas.ts:51]: Will fetch all authorizations when contracts are fetched form the server. This was moved from the wallet saga.

File: webapp/src/modules/contract/sagas.ts [hunk 8]
```diff
@@ -35,3 +47,206 @@ export function* handleFetchContractsRequest() {
...
+        authorizedAddress: rentals.address,
+        contractAddress: contract.address,
+        contractName: ContractName.ERC721,
+        chainId: contract.chainId,
+        type: AuthorizationType.APPROVAL
+      })
+    }
+  }
+
+  const stateAuthorizations: Authorization[] = yield select(getAuthorizations)
```
Comment (fzavalia) [inline webapp/src/modules/contract/sagas.ts:233]: In order to prevent duplication of authorizations, I'm removing authorizations that are already stored and just requesting the new ones.

File: webapp/src/modules/contract/selectors.ts [hunk 9]
```diff
@@ -33,10 +33,6 @@ export const getContract = createSelectorCreator(defaultMemoize, isEqual)<
       )
     )
 
-    if (!found) {
-      throw new Error(`Contract not found, query=${JSON.stringify(query)}`)
-    }
-
-    return found
+    return found || null
```
Comment (fzavalia) [inline webapp/src/modules/contract/selectors.ts:36]: Throwing an error here was messing things up so I removed it

File: webapp/src/modules/contract/utils.ts [hunk 10]
```diff
@@ -28,3 +34,60 @@ export function* getOrWaitForContracts() {
   const contracts: ReturnType<typeof getContracts> = yield select(getContracts)
   return contracts
 }
+
+export function upsertContracts(
```
Comment (fzavalia) [inline webapp/src/modules/contract/utils.ts:38]: This functions takes a list of contracts and upserts another list of contracts into it. 
This is because now, contracts are fetched on various occasions and we don't want duplications nor missing previously defined contracts.

File: webapp/src/modules/nft/sagas.ts [hunk 11]
```diff
@@ -68,6 +73,26 @@ function* handleFetchNFTsRequest(action: FetchNFTsRequestAction) {
...
+
+      if (!contractAddressesAndChainIds.has(nftContractAddressAndChainId)) {
+        arr.push(getStubMaticCollectionContract(nft.contractAddress))
+      }
+
+      return arr
+    }, [] as Contract[])
+
+    if (newContracts.length > 0) {
+      yield put(upsertContracts(newContracts))
```
Comment (fzavalia) [inline webapp/src/modules/nft/sagas.ts:93]: Static contracts are defined in the store from the beginning, meaning that nfts that have different addresses are warables or emotes.
For these contracts that do not exist in the store at the moment, I generate a stub contract for them to be available.

File: webapp/src/modules/nft/sagas.ts [hunk 12]
```diff
@@ -90,11 +115,17 @@ function* handleFetchNFTRequest(action: FetchNFTRequestAction) {
...
     yield call(getOrWaitForContracts)
 
-    const contract: ReturnType<typeof getContract> = yield select(getContract, {
-      address: contractAddress
+    let contract: ReturnType<typeof getContract> = yield select(getContract, {
+      address: contractAddress.toLowerCase()
     })
 
-    if (!contract || !contract.vendor) {
+    if (!contract) {
```
Comment (fzavalia) [inline webapp/src/modules/nft/sagas.ts:122]: Same as before, I generate the stub for the dynamic contract that is not present in the store.

File: webapp/src/modules/vendor/decentraland/ContractService.ts [hunk 13]
```diff
@@ -1,181 +1,10 @@
...
-} from '../services'
-import { Network as AppNetwork } from '../../contract/types'
+import { ContractService as ContractServiceInterface } from '../services'
 import { TransferType } from '../types'
 import { nftAPI } from './nft'
-import { config } from '../../../config'
-
-const network = config.get('NETWORK')! as AppNetwork
-
-export enum ContractName {
```
Comment (fzavalia) [inline webapp/src/modules/vendor/decentraland/ContractService.ts:14]: Moved this and contracts to the contracts.ts file

File: webapp/src/modules/wallet/sagas.ts [hunk 14]
```diff
@@ -29,193 +10,5 @@ const baseWalletSaga = createWalletSaga({
 })
 
 export function* walletSaga() {
-  yield all([baseWalletSaga(), fullWalletSaga()])
-}
-
-function* fullWalletSaga() {
-  yield takeEvery(CONNECT_WALLET_SUCCESS, handleWallet)
```
Comment (fzavalia) [inline webapp/src/modules/wallet/sagas.ts:36]: I don't need any of this anymore because authorisations are fetched differently now.

File: webapp/src/modules/contract/sagas.spec.ts (hunk 6 above)
Comment (fzavalia) [reply webapp/src/modules/contract/sagas.spec.ts]: Unskipped the tests 👍

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx [hunk 15]
```diff
@@ -23,18 +28,64 @@ const AuthorizationModal = (props: Props) => {
...
   const contract = getContract({
     address: authorization.authorizedAddress
   })
+
   const token = getContract({
     address: authorization.contractAddress
   })
 
+  const hasFetchedAuthorizations = useRef(false)
+  const hasFetchedContractName = useRef(false)
```
Comment (LautaroPetaccio) [inline webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:47]: I think we need a loader that shows the user that the authorization or the contract name is being fetched, right?

Comment (LautaroPetaccio) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:47]: Also, what if we initialize `hasFetchedContractName` to false if the contract does not have a name or has the default name set? That could avoid fetching the contract name if the user has already loaded it.

File: webapp/src/components/SettingsPage/SettingsPage.tsx (hunk 3 above)
Comment (LautaroPetaccio) [reply webapp/src/components/SettingsPage/SettingsPage.tsx:41]: If you want, you can create a ticket to make this improvement.

File: webapp/src/components/SettingsPage/SettingsPage.tsx (hunk 5 above)
Comment (LautaroPetaccio) [reply webapp/src/components/SettingsPage/SettingsPage.tsx:237]: Great catch!

File: webapp/src/modules/contract/utils.spec.ts [hunk 16]
```diff
@@ -0,0 +1,249 @@
...
+      getContractKeyFromNFT({
+        contractAddress: 'address',
+        chainId: ChainId.MATIC_MUMBAI
+      } as NFT)
+    ).toEqual('address-80001')
+  })
+})
+
+describe('when calling getAuthorizationKey', () => {
+  it('should return a string with the contract address and chain id', () => {
```
Comment (LautaroPetaccio) [inline webapp/src/modules/contract/utils.spec.ts:181]:
```suggestion
  it('should return a string that contains the address, the authorized address, the contract address and the chain Id', () => {
```

File: webapp/src/modules/contract/utils.spec.ts [hunk 17]
```diff
@@ -0,0 +1,249 @@
...
+        address: 'address',
+        category: NFTCategory.WEARABLE,
+        chainId: undefined,
+        name: STUB_MATIC_COLLECTION_CONTRACT_NAME,
+        network: Network.MATIC,
+        vendor: VendorName.DECENTRALAND
+      })
+    })
+  })
+})
```
Comment (LautaroPetaccio) [inline webapp/src/modules/contract/utils.spec.ts:206]: As it's only one case, you can remove the describe that is used for the context if you want and just have the address be lowercased:
```suggestion
describe('when calling getStubMaticCollectionContract', () => {
    it('should return stub matic collection contract with the address lowercased', () => {
      expect(getStubMaticCollectionContract('ADDRESS')).toEqual({
        address: 'address',
        category: NFTCategory.WEARABLE,
        chainId: undefined,
        name: STUB_MATIC_COLLECTION_CONTRACT_NAME,
        network: Network.MATIC,
        vendor: VendorName.DECENTRALAND
      })
    })
})
```
Also, why is the `chainId` undefined?

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx (hunk 1 above)
Comment (LautaroPetaccio) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:59]: What do you think about adding this Github comment as a code comment?

**Review by LautaroPetaccio — CHANGES_REQUESTED** [review]

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx (hunk 1 above)
Comment (fzavalia) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:62]: 👍

File: webapp/src/components/SettingsPage/SettingsPage.tsx (hunk 3 above)
Comment (fzavalia) [reply webapp/src/components/SettingsPage/SettingsPage.tsx:41]: https://github.com/decentraland/marketplace/issues/1167

File: webapp/src/modules/contract/sagas.ts (hunk 8 above)
Comment (fzavalia) [reply webapp/src/modules/contract/sagas.ts:237]: 👍

File: webapp/src/modules/contract/utils.ts (hunk 10 above)
Comment (fzavalia) [reply webapp/src/modules/contract/utils.ts:38]: But isn't merging some sort of upsert? It inserts contract that are not present, and updates contracts that are present.

File: webapp/src/modules/nft/sagas.ts (hunk 12 above)
Comment (fzavalia) [reply webapp/src/modules/nft/sagas.ts:127]: 👍

File: webapp/src/components/AuthorizationModal/AuthorizationModal.container.ts [hunk 18]
```diff
@@ -15,6 +17,7 @@ import {
   MapDispatch
 } from './AuthorizationModal.types'
 import AuthorizationModal from './AuthorizationModal'
+import { upsertContracts } from '../../modules/contract/actions'
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.container.ts]: 👍

File: webapp/src/components/SettingsPage/SettingsPage.container.ts [hunk 19]
```diff
@@ -15,14 +15,21 @@ import {
...
 import {
   MapStateProps,
   MapDispatch,
   MapDispatchProps
 } from './SettingsPage.types'
 import SettingsPage from './SettingsPage'
+import {
+  fetchContractsRequest,
+  FETCH_CONTRACTS_REQUEST
+} from '../../modules/contract/actions'
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/components/SettingsPage/SettingsPage.container.ts]: 👍

File: webapp/src/modules/nft/sagas.ts [hunk 20]
```diff
@@ -32,6 +37,8 @@ import {
   transferNFTransactionSubmitted
 } from './actions'
 import { NFT } from './types'
+import { upsertContracts } from '../contract/actions'
+import { Contract } from '../vendor/services'
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/modules/nft/sagas.ts:41]: 👍

File: webapp/src/modules/nft/sagas.spec.ts [hunk 21]
```diff
@@ -27,6 +33,15 @@ import { Account } from '../account/types'
 import { getContract, getContracts, getLoading } from '../contract/selectors'
 import { waitUntilRentalChangesStatus } from '../rental/utils'
 import { getRentalById } from '../rental/selectors'
+import { getChainIdByNetwork } from 'decentraland-dapps/dist/lib/eth'
+import { upsertContracts } from '../contract/actions'
+import { getStubMaticCollectionContract } from '../contract/utils'
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/modules/nft/sagas.spec.ts:38]: 👍

File: webapp/src/modules/contract/sagas.spec.ts [hunk 22]
```diff
@@ -21,7 +27,77 @@ describe.only('when handling the fetch contracts request', () => {
...
+          ],
+          [
+            select(getContract, {
+              name: contractNames.RENTALS,
+              network: Network.ETHEREUM
+            }),
+            {}
+          ],
+          [select(getAuthorizations), []]
+        ])
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/modules/contract/sagas.spec.ts:100]: The authorizations request is done in a different sagas that handles the fetchContractsSuccess. Still I'll add a test for what you are saying.

[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/modules/contract/sagas.spec.ts:202]: Done 👍

File: webapp/src/modules/contract/reducer.ts [hunk 23]
```diff
@@ -28,36 +40,50 @@ type ContractReducerAction =
...
+    }
+
+    case UPSERT_CONTRACTS: {
+      const { contracts } = action.payload
+
+      return {
+        ...state,
+        data: upsertContracts(state.data, contracts)
+      }
+    }
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/modules/contract/reducer.ts:85]: 👍

File: webapp/src/components/SettingsPage/SettingsPage.container.ts [hunk 24]
```diff
@@ -39,18 +46,18 @@ const mapState = (state: RootState): MapStateProps => {
   return {
     wallet,
     authorizations: getAuthorizations(state),
-    isLoadingAuthorization: isLoadingType(
-      getLoading(state),
-      FETCH_AUTHORIZATIONS_REQUEST
-    ),
+    isLoading:
+      isLoadingType(getLoading(state), FETCH_AUTHORIZATIONS_REQUEST) ||
+      isLoadingType(getContractLoading(state), FETCH_CONTRACTS_REQUEST),
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/components/SettingsPage/SettingsPage.container.ts:51]: The authorizations loader is there (the one for FETCH_AUTHORIZATIONS_REQUEST)

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx [hunk 25]
```diff
@@ -1,17 +1,22 @@
...
 } from 'decentraland-ui'
 import { t, T } from 'decentraland-dapps/dist/modules/translation/utils'
+import { getNetworkProvider } from 'decentraland-dapps/dist/lib/eth'
 
 import { locations } from '../../modules/routing/locations'
 import { isAuthorized } from '../SettingsPage/Authorization/utils'
 import { Authorization } from '../SettingsPage/Authorization'
 import { Props } from './AuthorizationModal.types'
+import { isStubMaticCollectionContract } from '../../modules/contract/utils'
+import ERC721ABI from '../../contracts/ERC721.json'
```
[the remark this answers is not in the document]
Comment (fzavalia) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:18]: 👍

File: webapp/src/components/AuthorizationModal/AuthorizationModal.tsx (hunk 15 above)
Comment (fzavalia) [reply webapp/src/components/AuthorizationModal/AuthorizationModal.tsx:47]: https://github.com/decentraland/marketplace/issues/1169 created the issue for the loader. 

For the second thing, the name will only be fetched if the contract has the name of a stub collection, so there will no unnecessary fetches.

File: webapp/src/components/SettingsPage/SettingsPage.container.ts (hunk 24 above)
[the remark this answers is not in the document]
Comment (LautaroPetaccio) [reply webapp/src/components/SettingsPage/SettingsPage.container.ts:51]: My bad 🤦

**Review by LautaroPetaccio — APPROVED** [review]
