### PR TITLE
fix: restore estate_ids on sanity

### LINKED ISSUE #540: Reset estate_id from broken parcels when running sanity-check

### PR DESCRIPTION
**Pull request by NicoSantangelo**
Closes #540

### CODE REVIEW

File: sanity/doctors/ParcelDoctor.js [hunk 1]
```diff
@@ -89,16 +89,21 @@ export class ParcelDiagnosis extends Diagnosis {
   }
 
   async prepare() {
-    const deletes = this.faultyParcels.map(parcel =>
-      BlockchainEvent.deleteByArgs('assetId', parcel.token_id)
-    )
+    let deletes = []
+    for (const parcel of this.faultyParcels) {
+      deletes = deletes.concat([
+        BlockchainEvent.deleteByArgs('assetId', parcel.token_id),
```
Comment (nachomazzara) [inline sanity/doctors/ParcelDoctor.js]: Why we dont check also the event name? Is there any way to delete something undesired?
