### PR TITLE
fix: Favorites visual fixes

### LINKED ISSUE #1622: When an item has 0 favorites, a pointer cursor appears in the 0's margin

### LINKED ISSUE #1626: When loading My lists page for the first time, the footer looks at the top of the page

### LINKED ISSUE #1627: When loading the My Lists page in Mobile, the Loader is not centered

### LINKED ISSUE #1628: When Loading the My Lists page in Mobile, the footer is in the middle of the screen instead of the bottom

### LINKED ISSUE #1630: Whislist title and counter are not aligned in mobile

### PR DESCRIPTION
**Pull request by kevinszuchet**
Closes #1622
Closes #1626
Closes #1627 
Closes #1628
Closes #1630

### CODE REVIEW

File: webapp/src/components/ListsPage/ListsPage.tsx [hunk 1]
```diff
@@ -33,13 +33,11 @@ const ListsPage = ({ wallet, isConnecting, onRedirect }: Props) => {
...
         {t('lists_page.default_title')}
       </Header>
-      {wallet ? (
-        <AssetBrowse
-          view={View.LISTS}
-          section={Section.LISTS}
-          vendor={VendorName.DECENTRALAND}
-        />
-      ) : null}
+      <AssetBrowse
```
Comment (LautaroPetaccio) [inline webapp/src/components/ListsPage/ListsPage.tsx:36]: By removing this, we'll be starting the fetch procedure upon loading the `AssetBrowse`. Is there a solution that can avoid this?

**Review by LautaroPetaccio — COMMENTED** [review]
Looks great, I just left a comment so we can talk about a different solution.

File: webapp/src/components/ListsPage/ListsPage.tsx [hunk 2]
```diff
@@ -20,26 +21,32 @@ const ListsPage = ({ wallet, isConnecting, onRedirect }: Props) => {
 
   useEffect(() => {
     if (!isConnecting && !wallet) {
-      onRedirect(locations.signIn(`${pathname}${search}`))
+      console.log(locations.signIn(`${pathname}${search}`))
```
Comment (LautaroPetaccio) [inline webapp/src/components/ListsPage/ListsPage.tsx:24]: This line replaced the onRedirect with a console log, would you mind reverting this change?

**Review by LautaroPetaccio — APPROVED** [review]
