### PR TITLE
fix: check name/descriptions correctly

### LINKED ISSUE #400: Estate with no name when editing should not be allowed

### PR DESCRIPTION
**Pull request by NicoSantangelo**
plz testerino 🙏 
Closes #400

### CODE REVIEW

File: shared/asset.js [hunk 1]
```diff
@@ -184,12 +184,12 @@ export function getType(asset, publications, wallet) {
   return TYPES.taken
 }
 
-export function isValidName(name) {
-  return name <= 50
+export function isValidName(name = '') {
+  return name.length > 0 && name.length <= 50
```
Comment (nachomazzara) [inline shared/asset.js]: This could be `name.length && name.length <= 50`

Comment (cazala) [reply shared/asset.js]: TypeScript doesn't think the same :P although javascript allows stuff like that let's stick to consistent return values (in this case, always return a boolean)
