### PR TITLE
fix: handle empty estate

### LINKED ISSUE #384: Add a message when you visit an empty Estate

### PR DESCRIPTION
**Pull request by cazala**
Closes #384 

Currently empty (aka deleted) estates show a broken page (only navbar and footer, and footer is _en cualquiera_)

This PR adds a screen for empty estates:

screen shot 2018-08-28 at 4 15 48 pm

### CODE REVIEW

**Comment by NicoSantangelo** [comment]
The changeset looks 💯 but I'd like to revise the wording we use for this action. I know I raised this concern before...but I'm annoying like that.

Given that supporting empty states is on the roadmap https://github.com/decentraland/marketplace/projects/4 I think that we can change `delete` for something like `dissolve`

File: webapp/src/components/EstateDetailPage/EstateDetailPage.js [hunk 1]
```diff
@@ -41,27 +41,26 @@ export default class EstateDetailPage extends React.PureComponent {
...
-                allParcels={allParcels}
-                estate={estate}
-                isOwner={isOwner}
-                onViewAssetClick={onViewAssetClick}
-                onEditParcels={onEditParcels}
-                onEditMetadata={onEditMetadata}
-              />
-            )
-          ) : null
+          estate.data.parcels.length > 0 &&
```
Comment (nachomazzara) [inline webapp/src/components/EstateDetailPage/EstateDetailPage.js]: I think we can remove `estate.data.parcels.length > 0` I added it to not render anything in case the estate is empty. As we have that check [here](https://github.com/decentraland/marketplace/pull/389/files#diff-dc94e71ea3fc145084f572f535ae7185R50) maybe it is obsolete to have it here too
