### PR TITLE
fix: Don't allow renting with address zero

### LINKED ISSUE #1177: Prevent adding the zero address as operator when renting
Prevent adding the zero address as operator when renting

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
Disallow rents with the beneficiary as 0x0...0.
Closes #1177

### CODE REVIEW

File: webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx [hunk 1]
```diff
@@ -19,6 +19,8 @@ import { ManaField } from '../../ManaField'
 import { Props } from './ConfirmRentModal.types'
 import styles from './ConfirmRentModal.module.css'
 
+const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'
```
Comment (fzavalia) [inline webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx:22]: If using ethers, there is a constant for the zero address that we can use instead of hardcoding it like this

**Review by fzavalia — CHANGES_REQUESTED** [review]

File: webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx (hunk 1 above)
Comment (fzavalia) [reply webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx:22]: https://docs.ethers.org/v5/api/utils/constants/#constants-AddressZero

Comment (fzavalia) [reply webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx:22]: Might be better to use that instead

Comment (LautaroPetaccio) [reply webapp/src/components/Modals/ConfirmRentModal/ConfirmRentModal.tsx]: Totally forgot about the ethers constants. Great catch!

**Review by fzavalia — APPROVED** [review]
