### PR TITLE
fix: Use page name instead of view

### LINKED ISSUE #1592: When switching from My Assets to My List the items can display the on sell icon
## 🎉 Description

When switching a bit fast from My Assets to My List, the view gets stuck at the one that is used in My Assets. This might be due to a race condition on the `setView` action that ends up overwriting the views when switching between one another.

Steps to reproduce:
1. Have several items favorited and some owned ones in the wallet.
2. Go to My Assets and kind of fast, click on the My List tab
3. The items in My List tab will appear with the on sale icon.

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
This PR introduces the `getPageName` selector which replaces the `getView` selector in cases where we want to know what the page the user is in.

Closes #1592

### CODE REVIEW

File: webapp/src/modules/routing/selectors.ts [hunk 1]
```diff
@@ -523,3 +524,77 @@ export const getIsBuyWithCardPage = createSelector<RootState, string, boolean>(
     return withCard !== null && withCard === 'true'
   }
 )
+
+const buildExactMatchProps = (path: string) => {
+  return { path, exact: true }
+}
+
+export const getPageName = createSelector<RootState, string, PageName>(
```
Comment (kevinszuchet) [inline webapp/src/modules/routing/selectors.ts:532]: WDTY about having a map with the locations and the page name, maybe in another file? I think the selector will be clearer.

**Review by kevinszuchet — COMMENTED** [review]
Great solution!

I left a comment to discuss if we can write the new selector clearer.

**Review by kevinszuchet — APPROVED** [review]
