### PR TITLE
fix: Don't open in builder if not claimed

### LINKED ISSUE #1000: The "Open in builder" button is not disabled when the user has not claimed the LAND yet
The "Open in builder" button is not disabled when the user has not claimed the LAND. Clicking on the "Open in builder" button will open the builder but the user won't see anything as the Rental Contract is the owner of the LAND.

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
This PR does two things:
- Disallows using the "open in builder" button until the Land is claimed, as the builder won't show the Land you don't currently own.
- Changes the mobile hook to `useMobileMediaQuery`.

Closes #1000

### CODE REVIEW

File: webapp/src/components/ManageAssetPage/ManageAssetPage.tsx [hunk 1]
```diff
@@ -95,13 +98,48 @@ export const ManageAssetPage = (props: Props) => {
...
-                                <Button
-                                  className={styles.builderButton}
-                                  primary
-                                  onClick={() => handleOpenInBuilder(asset)}
-                                >
-                                  {t('manage_asset_page.open_in_builder')}
-                                </Button>
+                                <Popup
+                                  content={
+                                    'This action is locked until the rent has finished and (or) the Land has been claimed back'
```
Comment (juanmahidalgo) [inline webapp/src/components/ManageAssetPage/ManageAssetPage.tsx:103]:
```suggestion
                                    t('manage_asset_page.land_is_locked')
```
right?

**Review by juanmahidalgo — APPROVED** [review]

File: webapp/src/components/ManageAssetPage/ManageAssetPage.tsx [hunk 2]
```diff
@@ -95,13 +98,48 @@ export const ManageAssetPage = (props: Props) => {
...
+                                      isLandLocked(
+                                        wallet.address,
+                                        rental,
+                                        asset
+                                      )
+                                    )
+                                  }
+                                  trigger={
+                                    <span>
+                                      {
```
Comment (juanmahidalgo) [inline webapp/src/components/ManageAssetPage/ManageAssetPage.tsx:119]:
```suggestion
                                      
```
Are these brackets necessary?

File: webapp/src/components/ManageAssetPage/ManageAssetPage.tsx (hunk 1 above)
Comment (LautaroPetaccio) [reply webapp/src/components/ManageAssetPage/ManageAssetPage.tsx:103]: Great catch!

File: webapp/src/components/ManageAssetPage/ManageAssetPage.tsx (hunk 2 above)
Comment (LautaroPetaccio) [reply webapp/src/components/ManageAssetPage/ManageAssetPage.tsx:119]: They're totally unnecessary, removed them!

**Review by juanmahidalgo — APPROVED** [review]
LGTM!
