### PR TITLE
fix: asset image badges on my assets -> land

### LINKED ISSUE #1317: Land View in my assets page displays badges in a wrong position
In the LAND detail view in the Marketplace - My assets - LAND, the coordinates and the button to see the land in-world are on top of the Open in Builder CTA. It should be on top of the LAND thumbnail as in desktop but it should not overlap with the main CTA

Move the badges to the asset image component

### PR DESCRIPTION
**Pull request by flobarreto**
closes #1317 

web 
image

tablet
image

mobile
image

### CODE REVIEW

File: webapp/src/components/ManageAssetPage/Map/Map.tsx [hunk 1]
```diff
@@ -1,60 +1,13 @@
-import React, { useMemo } from 'react'
-import { NFTCategory } from '@dcl/schemas'
-import { Badge } from 'decentraland-ui'
+import React from 'react'
 import { AssetImage } from '../../AssetImage'
-import { JumpIn } from '../../AssetPage/JumpIn'
-import { Coordinate } from '../../Coordinate'
 import { Props } from './Map.types'
-import styles from './Map.module.css'
```
Comment (fzavalia) [inline webapp/src/components/ManageAssetPage/Map/Map.tsx:8]: Can `Map.module.css` if it not imported anymore?

File: webapp/src/components/AssetImage/AssetImage.tsx [hunk 2]
```diff
@@ -495,12 +508,56 @@ const AssetImageWrapper = (props: Props) => {
...
+                  </>
+                ) : (
+                  <Coordinate
+                    className="coordinates"
+                    x={coordinates.x}
+                    y={coordinates.y}
+                  />
+                )}
+                <JumpIn compact x={coordinates.x} y={coordinates.y} />
+                {console.log('floooooo')}
```
Comment (fzavalia) [inline webapp/src/components/AssetImage/AssetImage.tsx:556]: Remove the log

**Review by fzavalia — CHANGES_REQUESTED** [review]

**Review by fzavalia — APPROVED** [review]
