### PR TITLE
fix: Avoid showing play showcase if the SW does not have a video

### LINKED ISSUE #2009: Avoid showing the button "Play Showcase Video" if the Smart Wearable doesn't have one
## 🎉 Description

Given that some Smart Wearables don't and won't have a Showcase Video, and that there are some old ones that were created without the chance of adding a preview, we should hide the button "Play Showcase Video" from the Asset Image if the Smart Wearable doesn't have one.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnlHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ab78200f7fa1604dcd3f73d38a64f82108dc5c07/image.png)

### PR DESCRIPTION
**Pull request by kevinszuchet**
Close #2009

### CODE REVIEW

File: webapp/src/components/Modals/SmartWearableVideoShowcaseModal/SmartWearableVideoShowcaseModal.tsx [hunk 1]
```diff
@@ -1,30 +1,17 @@
...
+import React from 'react'
 import { t } from 'decentraland-dapps/dist/modules/translation/utils'
 import { Modal } from 'decentraland-dapps/dist/containers'
 import { Loader, ModalNavigation } from 'decentraland-ui'
-import { builderAPI } from '../../../modules/vendor/decentraland/builder/api'
-import { getSmartWearableVideoShowcase } from '../../../lib/asset'
 import { VIDEO_TEST_ID } from './constants'
 import { Props } from './SmartWearableVideoShowcaseModal.types'
 import styles from './SmartWearableVideoShowcaseModal.module.css'
+import { builderAPI } from '../../../modules/vendor/decentraland/builder/api'
```
Comment (cyaiox) [inline webapp/src/components/Modals/SmartWearableVideoShowcaseModal/SmartWearableVideoShowcaseModal.tsx:8]: could you please move this import above?

**Review by cyaiox — APPROVED** [review]
